### ISSUE TITLE
Rqt for melodic doesn't work with Python3.9

### ISSUE THREAD

**Issue by bionade24** [ros-melodic-arch/ros-melodic-rqt#4]
```
CompositePluginProvider.discover() could not diass 'rqt_gui.rospkg_plugin_provider.RospkgPluginProvider'>":
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python3.9/site-packages/qt_gui/co 57, in discover
    plugin_descriptors = plugin_provider.discover(discovery_da
  File "/opt/ros/melodic/lib/python3.9/site-packages/rqt_gui/rin discover
    plugin_descriptors += self._parse_plugin_xml(package_name,
  File "/opt/ros/melodic/lib/python3.9/site-packages/rqt_gui/r in _parse_plugin_xml
    for library_el in root.getiterator('library'):
AttributeError: 'ElementTree' object has no attribute 'getiter

CompositePluginProvider.discover() could not discover plugins ursive_plugin_provider.RecursivePluginProvider'>":
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python3.9/site-packages/qt_gui/co 57, in discover
    plugin_descriptors = plugin_provider.discover(discovery_da
  File "/opt/ros/melodic/lib/python3.9/site-packages/qt_gui/re 53, in discover
    plugin_descriptors = self._plugin_provider.discover(discov
  File "/opt/ros/melodic/lib/python3.9/site-packages/rqt_gui/rin discover
    plugin_descriptors += self._parse_plugin_xml(package_name,
  File "/opt/ros/melodic/lib/python3.9/site-packages/rqt_gui/r in _parse_plugin_xml
    for library_el in root.getiterator('library'):
AttributeError: 'ElementTree' object has no attribute 'getiter
```
https://stackoverflow.com/questions/64264563/attributeerror-elementtree-object-has-no-attribute-getiterator-when-trying

**Comment by bionade24** [comment]
> ```
> CompositePluginProvider.discover() could not diass 'rqt_gui.rospkg_plugin_provider.RospkgPluginProvider'>":
> Traceback (most recent call last):
>   File "/opt/ros/melodic/lib/python3.9/site-packages/qt_gui/co 57, in discover
>     plugin_descriptors = plugin_provider.discover(discovery_da
>   File "/opt/ros/melodic/lib/python3.9/site-packages/rqt_gui/rin discover
>     plugin_descriptors += self._parse_plugin_xml(package_name,
>   File "/opt/ros/melodic/lib/python3.9/site-packages/rqt_gui/r in _parse_plugin_xml
>     for library_el in root.getiterator('library'):
> AttributeError: 'ElementTree' object has no attribute 'getiter
> 
> CompositePluginProvider.discover() could not discover plugins ursive_plugin_provider.RecursivePluginProvider'>":
> Traceback (most recent call last):
>   File "/opt/ros/melodic/lib/python3.9/site-packages/qt_gui/co 57, in discover
>     plugin_descriptors = plugin_provider.discover(discovery_da
>   File "/opt/ros/melodic/lib/python3.9/site-packages/qt_gui/re 53, in discover
>     plugin_descriptors = self._plugin_provider.discover(discov
>   File "/opt/ros/melodic/lib/python3.9/site-packages/rqt_gui/rin discover
>     plugin_descriptors += self._parse_plugin_xml(package_name,
>   File "/opt/ros/melodic/lib/python3.9/site-packages/rqt_gui/r in _parse_plugin_xml
>     for library_el in root.getiterator('library'):
> AttributeError: 'ElementTree' object has no attribute 'getiter
> ```
> 
> https://stackoverflow.com/questions/64264563/attributeerror-elementtree-object-has-no-attribute-getiterator-when-trying

@fmauch What do you think about this? I would tend to go back to python3.8 or python3.7 instead of reopening patch hell every python release in the future.

**Comment by bionade24** [comment]
@fmauch: Btw, if you want to watch all repos of this org, here's a snippet.
```
from github import Github
gh = Github("GH_OAUTH_TOKEN")
g = gh.get_organization("ros-melodic-arch")
auth_user = gh.get_user()
print(auth_user.name)
for repo in g.get_repos():
    print(repo.name)
    auth_user.add_to_watched(repo)
```

**Comment by fmauch** [comment]
I would rather prefer trying to get patches merged upstream.

**Comment by bionade24** [comment]
> I would rather prefer trying to get patches merged upstream.

It probably is already patched upstream, but only for noetic and never makes it way back to melodic. I look.

**Comment by bionade24** [comment]
Ok, it's probably easy to patch it: https://github.com/ros-visualization/rqt/issues/240

**Comment by bionade24** [comment]
https://github.com/ros-visualization/rqt/pull/241

**Comment by bionade24** [comment]
Actual patch: https://github.com/ros-visualization/rqt/commit/80c0ae8b8a58a6b1e970ea3e5f3277f2a38cdd2f.patch (Can be used as download source in PKGBUILD)

**Comment by fmauch** [comment]
@bionade24 you assigned this to yourself. I am assuming that you update the PKGBUILD? Otherwise I would do it.

**Comment by bionade24** [comment]
Am Montag, 18. Januar 2021 12:10:01 CET schrieb Felix Exner:
> @bionade24 you assigned this to yourself. I am assuming that 
> you update the PKGBUILD? Otherwise I would do it.
>

I would do it today evening ETC, do it before if you want.

**Comment by fmauch** [comment]
Fixed in https://github.com/ros-melodic-arch/ros-melodic-rqt-gui/commit/16537769d7176f97bd8dec625459e6d8d3fcbedc

**Comment by fmauch** [comment]
As this issue is in the wrong repo and the patch should get finally applied upstream, how should we proceed?

**Comment by bionade24** [comment]
> As this issue is in the wrong repo and the patch should get finally applied upstream, how should we proceed?

Open an issue in rqt-gui, mark it with label patched. Wait until it gets hopefully into a melodic release, which will probably take a month or so.
